global:
  scrape_interval: 10s
  evaluation_interval: 10s


scrape_configs:
#  - job_name: 'user_service'
#    eureka_sd_configs:
#      - server: 'http://eureka-server:8761/eureka/'
#        services_query_path: '/eureka/apps/user-service'  # Adjust this path to match the Eureka metadata for your service
#        refresh_interval: 30s  # Adjust as needed
#    metrics_path: '/actuator/prometheus'
#
#    static_configs:
#      - targets: ['user-service:8080']
#        labels:
#          application: 'User Service Application'
#
#  - job_name: 'authentication_service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: [ 'authentication-service:8080' ]
#        labels:
#          application: 'Authentication Service Application'


  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'User Service Application'


  - job_name: 'authentication_service'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'Authentication Service Application'